package comp5619.backend.controller;

import comp5619.backend.models.Booking;
import comp5619.backend.repository.BookingRepository;

import java.sql.Time;
import java.sql.Timestamp;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.apache.tomcat.util.buf.StringCache;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller // This means that this class is a Controller
@RequestMapping(path = "/bookings")
public class BookingController {

    @Autowired // This means to get the bean called commentRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private BookingRepository bookingRepository;

    @GetMapping(path = "/getAllBookings/{id}")
    public @ResponseBody ResponseEntity<List<Map<String, Object>>> getAllBookingsByUserId(@PathVariable(name = "id") String user_id) {
        List<Map<String, Object>> result = bookingRepository.getAllBookingByUserId(user_id);
        if (result.size() == 0) {
            return ResponseEntity.status(HttpStatus.NO_CONTENT).body(result);
        }
        return ResponseEntity.status(HttpStatus.OK).body(result);
    }

    @GetMapping(path = "/getAllShopBookings/{shopId}")
    public @ResponseBody ResponseEntity<List<Map<String, Object>>> getAllBookingsByShopId(@PathVariable(name = "shopId") String shopId) {
        List<Map<String, Object>> result = bookingRepository.getAllBookingsByShopId(shopId);
        if (result.size() == 0) {
            return ResponseEntity.status(HttpStatus.NO_CONTENT).body(result);
        }
        return ResponseEntity.status(HttpStatus.OK).body(result);
    }

    @PostMapping(path = "/deleteBooking")
    public @ResponseBody ResponseEntity<Object> deleteBookingById(@RequestBody Map<String, String> params) {

        String id = params.get("id");

        Map<String,Object> result = bookingRepository.getBookingById(id);

        if (result.size() == 0) {
            return ResponseEntity.status(HttpStatus.NO_CONTENT).body("No Content Found");
        }

        bookingRepository.deleteBookingById(id);

        return ResponseEntity.status(HttpStatus.OK).body("Update Success");
    }

    @PostMapping(path = "/add")
    public @ResponseBody ResponseEntity<Map<String, Object>> addService(@RequestBody Map<String, String> params) {
        Map<String, Object> response = new HashMap<>();

//        SimpleDateFormat source = new SimpleDateFormat("YYYY-MM-DD HH:mm");

        Booking newBooking = new Booking();
        newBooking.setPickUp(Integer.parseInt(params.get("pickup")));
        newBooking.setService_id(Integer.parseInt(params.get("service_id")));
        newBooking.setShopId(Integer.parseInt(params.get("shop_id")));
        newBooking.setUserId(Integer.parseInt(params.get("user_id")));
        try {
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd hh:mm");
            Date parsedDate = dateFormat.parse(params.get("time"));
            Timestamp timestamp = new java.sql.Timestamp(parsedDate.getTime());

            newBooking.setTime(timestamp);
        } catch (Exception e) {
            System.out.println(e);
            response.put("Message", "Invalid Time");
            return ResponseEntity.status(HttpStatus.BAD_REQUEST).body(response);
        }

        bookingRepository.save(newBooking);

        response.put("Message", "Make Booking Success");
        return ResponseEntity.status(HttpStatus.OK).body(response);
    }
}
