package comp5619.backend.controller;

import comp5619.backend.models.Comments;
import comp5619.backend.repository.CommentRepository;

import java.sql.Time;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import static java.lang.Float.parseFloat;

@Controller // This means that this class is a Controller
@RequestMapping(path = "/comments")
public class CommentsController {

    @Autowired // This means to get the bean called commentRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private CommentRepository commentRepository;

//    @PostMapping(path = "/addComment")
//    public @ResponseBody ResponseEntity<Map<String, Object>> addComment(@RequestBody Map<String, String> params) {
//
//        Map<String, Object> response = new HashMap<>();
//
//        response.put("Message", "Create Comment Success");
//        return ResponseEntity.status(HttpStatus.OK).body(response);
//    }
}
