package comp5619.backend.controller;

import comp5619.backend.models.Service;
import comp5619.backend.repository.ServiceRepository;

import java.util.List;
import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import static java.lang.Float.parseFloat;

@Controller // This means that this class is a Controller
@RequestMapping(path = "/service")
public class ServiceController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private ServiceRepository serviceRepository;

    @GetMapping(path = "/getServiceDetailById/{id}")
    public @ResponseBody ResponseEntity<Map<String, Object>> getServiceDetailById(@PathVariable(name = "id") String id) {
        Map<String, Object> result = serviceRepository.getServiceDetailById(id);
        return ResponseEntity.status(HttpStatus.OK).body(result);
    }

    @GetMapping(path = "/getMapInfoById/{id}")
    public @ResponseBody ResponseEntity<Map<String, Object>> getMapInfoById(@PathVariable(name = "id") String id) {
        Map<String, Object> result = serviceRepository.getMapInfoById(id);
        return ResponseEntity.status(HttpStatus.OK).body(result);
    }

}
